# Generated by Django 5.1.6 on 2025-03-20 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_offer', '0001_initial'),
        ('postulant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('undergraduate_title', models.TextField()),
                ('postgraduate_title', models.TextField(blank=True, null=True)),
                ('motivation', models.TextField()),
                ('resume', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('application_date', models.DateField()),
                ('applicant_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulant.postulant', to_field='document_id')),
                ('job_offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_offer.joboffer')),
            ],
        ),
    ]
