# Generated by Django 5.2 on 2025-05-17 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_offer', '0003_alter_joboffer_talent_director_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('undergraduate_title', models.TextField()),
                ('postgraduate_title', models.TextField(blank=True, null=True)),
                ('motivation', models.TextField()),
                ('resume', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('application_date', models.DateField()),
                ('applicant_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job_offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_offer.joboffer')),
            ],
            options={
                'db_table': 'Postulation',
            },
        ),
    ]
