# Generated by Django 5.2 on 2025-05-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('undergraduate_title', models.TextField()),
                ('postgraduate_title', models.TextField(blank=True, null=True)),
                ('motivation', models.TextField()),
                ('resume', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('application_date', models.DateField()),
            ],
            options={
                'db_table': 'Postulation',
            },
        ),
    ]
