# Generated by Django 5.2 on 2025-07-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulation',
            name='application_date',
            field=models.DateTimeField(),
        ),
    ]
