# Generated by Django 5.1.6 on 2025-03-20 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_offer', '0002_alter_joboffer_table'),
        ('postulant', '0002_alter_postulant_table'),
        ('postulation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobApplication',
            new_name='Postulation',
        ),
        migrations.AlterModelTable(
            name='postulation',
            table='Postulation',
        ),
    ]
