# Generated by Django 5.1.6 on 2025-03-20 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulant', '0003_remove_postulant_id_alter_postulant_document_id'),
        ('postulation', '0002_rename_jobapplication_postulation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulation',
            name='applicant_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulant.postulant'),
        ),
    ]
