# Generated by Django 5.2 on 2025-07-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulation', '0002_alter_postulation_application_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulation',
            name='postgraduate_support',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='postulation',
            name='resume_support',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='postulation',
            name='undergraduate_support',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='postulation',
            name='motivation',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='postulation',
            name='resume',
            field=models.TextField(default=''),
        ),
    ]
