# Generated by Django 5.2 on 2025-07-22 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulation', '0003_postulation_postgraduate_support_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulation',
            name='postgraduate_support',
            field=models.FileField(default='postgraduate/', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='postulation',
            name='resume_support',
            field=models.FileField(upload_to='curriculums/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='postulation',
            name='undergraduate_support',
            field=models.FileField(default='undergraduate/', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
