# Generated by Django 5.1.6 on 2025-03-20 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talentDirector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='talentdirector',
            table='TalentDirector',
        ),
    ]
