# Generated by Django 5.1.6 on 2025-03-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('responsibilities', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('education_level', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=10)),
                ('other_requirements', models.TextField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('talent_director_document', models.CharField(max_length=15)),
            ],
        ),
    ]
